# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fHoYlpG3ecdKBafPYF6tc535Dg5gA3_8
"""

import pandas as pd
import numpy as py
import io
import matplotlib.pyplot as mlp
import seaborn as sb
import sklearn as sklearn

from google.colab import files
uploaded=files.upload()

mynet=pd.read_csv("hari.csv")
mynet

mynet.head()

m=mynet.iloc[:,:-1].values
n=mynet.iloc[:,1].values

from sklearn.model_selection import train_test_split
m_train,m_test,n_train,n_test=train_test_split(m,n,test_size=0.2,random_state=0)

y_pred=regressor.predict(m_test)
y_pred



from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(m_train,n_train)

mlp.scatter(m_train,n_train,color='red')
mlp.plot(m_train,regressor.predict(m_train),color='blue')
mlp.title("Salary vs Experience (Training set)")

mlp.xlabel("Years of experience")
mlp.ylabel("Salaries")
mlp.show()

